language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install --upgrade pip
  - pip install "setuptools>=28.6.1"
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - flake8 .
cache: pip
